USE task4db;
CREATE TABLE Flower(
		Id INT PRIMARY KEY IDENTITY NOT NULL,
		Name NVARCHAR(30) NOT NULL
)

CREATE TABLE Plantation(
	Id INT PRIMARY KEY IDENTITY NOT NULL,
	Name NVARCHAR(30) NOT NULL,
	Adress NVARCHAR(30) NOT NULL
)
CREATE TABLE PlantationFlower(
	 FlowerId INT NOT NULL FOREIGN KEY REFERENCES Flower(Id),
	 PlantationId INT NOT NULL FOREIGN KEY REFERENCES Plantation(Id),
	 Ammount INT NOT NULL,
	 PRIMARY KEY(FlowerId,PlantationId)
) 
CREATE TABLE Warehouse(
	Id INT PRIMARY KEY IDENTITY NOT NULL,
	Name NVARCHAR(30) NOT NULL,
	Adress NVARCHAR(30) NOT NULL

)
CREATE TABLE WarehouseFlower(
		FlowerId INT NOT NULL FOREIGN KEY REFERENCES Flower(Id),
		WarehouseId INT NOT NULL FOREIGN KEY REFERENCES Warehouse(Id),
		Amount INT NOT NULL,
		PRIMARY KEY(FlowerId,WarehouseId)
)
CREATE  TABLE Supply(
	Id INT PRIMARY KEY IDENTITY NOT NULL,
	PlantationId INT NOT NULL FOREIGN KEY REFERENCES Plantation(Id),
	WarehouseId INT NOT NULL FOREIGN KEY REFERENCES Warehouse(Id),
	ScheduledDate DATE NOT NULL,
	ClosedDate DATE NOT NULL,
	Status NVARCHAR(30)
) 
CREATE TABLE SupplyFlower(
		FlowerId INT NOT NULL FOREIGN KEY REFERENCES Flower(Id),
		SupplyId INT NOT NULL FOREIGN KEY REFERENCES Supply(Id),
		Amount INT NOT NULL
		PRIMARY KEY(FlowerId,SupplyId)
)